version: '2'
services:
  external_employment_stats-mongodb:
    image: mongo:4.0.12
    ports:
      - '27017:27017'
    # volumes:
    #     - ~/volumes/jhipster/external_employment_stats/mongodb/:/data/db/
