version: '2'
services:
  main_status-postgresql:
    image: postgres:11.5
    # volumes:
    #     - ~/volumes/jhipster/main_status/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=main_status
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
