version: '2'
services:
  external_estimation-mongodb:
    image: mongo:4.0.12
    ports:
      - '27017:27017'
    command: mongos --configdb external_estimation-mongodb-config
  external_estimation-mongodb-node:
    build:
      context: .
      dockerfile: mongodb/MongoDB.Dockerfile
    command: mongod --replSet rs1 --noprealloc --smallfiles
  external_estimation-mongodb-config:
    image: mongo:4.0.12
    container_name: external_estimation-mongodb-config
    command: mongod --noprealloc --smallfiles --configsvr --dbpath /data/db
